//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tripodmaps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tripodmaps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _000 {
            get {
                object obj = ResourceManager.GetObject("_000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddTableHS1 {
            get {
                object obj = ResourceManager.GetObject("AddTableHS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddTableHS3 {
            get {
                object obj = ResourceManager.GetObject("AddTableHS3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_clock_small2 {
            get {
                object obj = ResourceManager.GetObject("ajax_clock_small2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader_big {
            get {
                object obj = ResourceManager.GetObject("ajax_loader_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader_snake {
            get {
                object obj = ResourceManager.GetObject("ajax_loader_snake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader_snake1 {
            get {
                object obj = ResourceManager.GetObject("ajax_loader_snake1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_ltr2 {
            get {
                object obj = ResourceManager.GetObject("arrow_ltr2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_rtl2 {
            get {
                object obj = ResourceManager.GetObject("arrow_rtl2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_calendar2 {
            get {
                object obj = ResourceManager.GetObject("b_calendar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_docsql1 {
            get {
                object obj = ResourceManager.GetObject("b_docsql1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_docsql3 {
            get {
                object obj = ResourceManager.GetObject("b_docsql3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_drop {
            get {
                object obj = ResourceManager.GetObject("b_drop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_drop2 {
            get {
                object obj = ResourceManager.GetObject("b_drop2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_edit2 {
            get {
                object obj = ResourceManager.GetObject("b_edit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_firstpage {
            get {
                object obj = ResourceManager.GetObject("b_firstpage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_firstpage2 {
            get {
                object obj = ResourceManager.GetObject("b_firstpage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_home2 {
            get {
                object obj = ResourceManager.GetObject("b_home2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_lastpage {
            get {
                object obj = ResourceManager.GetObject("b_lastpage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_lastpage2 {
            get {
                object obj = ResourceManager.GetObject("b_lastpage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_nextpage {
            get {
                object obj = ResourceManager.GetObject("b_nextpage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_nextpage2 {
            get {
                object obj = ResourceManager.GetObject("b_nextpage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_prevpage {
            get {
                object obj = ResourceManager.GetObject("b_prevpage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_prevpage2 {
            get {
                object obj = ResourceManager.GetObject("b_prevpage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_print {
            get {
                object obj = ResourceManager.GetObject("b_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_print2 {
            get {
                object obj = ResourceManager.GetObject("b_print2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_save {
            get {
                object obj = ResourceManager.GetObject("b_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_save2 {
            get {
                object obj = ResourceManager.GetObject("b_save2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_search2 {
            get {
                object obj = ResourceManager.GetObject("b_search2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_tblexport2 {
            get {
                object obj = ResourceManager.GetObject("b_tblexport2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_tblimport2 {
            get {
                object obj = ResourceManager.GetObject("b_tblimport2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_usradd2 {
            get {
                object obj = ResourceManager.GetObject("b_usradd2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_usrcheck2 {
            get {
                object obj = ResourceManager.GetObject("b_usrcheck2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_usrdrop2 {
            get {
                object obj = ResourceManager.GetObject("b_usrdrop2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_usredit2 {
            get {
                object obj = ResourceManager.GetObject("b_usredit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_usrlist2 {
            get {
                object obj = ResourceManager.GetObject("b_usrlist2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_view2 {
            get {
                object obj = ResourceManager.GetObject("b_view2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bd_drop2 {
            get {
                object obj = ResourceManager.GetObject("bd_drop2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bd_empty2 {
            get {
                object obj = ResourceManager.GetObject("bd_empty2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bd_firstpage2 {
            get {
                object obj = ResourceManager.GetObject("bd_firstpage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bd_lastpage2 {
            get {
                object obj = ResourceManager.GetObject("bd_lastpage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bd_nextpage2 {
            get {
                object obj = ResourceManager.GetObject("bd_nextpage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bd_prevpage2 {
            get {
                object obj = ResourceManager.GetObject("bd_prevpage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chat2 {
            get {
                object obj = ResourceManager.GetObject("Chat2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Coffee {
            get {
                object obj = ResourceManager.GetObject("Coffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DATABASE2 {
            get {
                object obj = ResourceManager.GetObject("DATABASE2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dining {
            get {
                object obj = ResourceManager.GetObject("Dining", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditTableHS1 {
            get {
                object obj = ResourceManager.GetObject("EditTableHS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditTableHS3 {
            get {
                object obj = ResourceManager.GetObject("EditTableHS3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favicon1 {
            get {
                object obj = ResourceManager.GetObject("favicon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favicon2 {
            get {
                object obj = ResourceManager.GetObject("favicon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Find_icon1616 {
            get {
                object obj = ResourceManager.GetObject("Find_icon1616", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Find_icon2424 {
            get {
                object obj = ResourceManager.GetObject("Find_icon2424", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Find_icon3232 {
            get {
                object obj = ResourceManager.GetObject("Find_icon3232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Find_icon4848 {
            get {
                object obj = ResourceManager.GetObject("Find_icon4848", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag2 {
            get {
                object obj = ResourceManager.GetObject("Flag2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap garage {
            get {
                object obj = ResourceManager.GetObject("garage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap garmin_logo {
            get {
                object obj = ResourceManager.GetObject("garmin_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Globe_icon1616 {
            get {
                object obj = ResourceManager.GetObject("Globe_icon1616", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Globe_icon2424 {
            get {
                object obj = ResourceManager.GetObject("Globe_icon2424", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Globe_icon3232 {
            get {
                object obj = ResourceManager.GetObject("Globe_icon3232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Globe_icon4848 {
            get {
                object obj = ResourceManager.GetObject("Globe_icon4848", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gov {
            get {
                object obj = ResourceManager.GetObject("gov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_icon1616 {
            get {
                object obj = ResourceManager.GetObject("Help_icon1616", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_icon2424 {
            get {
                object obj = ResourceManager.GetObject("Help_icon2424", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_icon3232 {
            get {
                object obj = ResourceManager.GetObject("Help_icon3232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_icon4848 {
            get {
                object obj = ResourceManager.GetObject("Help_icon4848", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home2 {
            get {
                object obj = ResourceManager.GetObject("Home2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hospitals {
            get {
                object obj = ResourceManager.GetObject("Hospitals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_new {
            get {
                object obj = ResourceManager.GetObject("icon_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_new2 {
            get {
                object obj = ResourceManager.GetObject("icon_new2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_open2 {
            get {
                object obj = ResourceManager.GetObject("icon_open2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_pan2 {
            get {
                object obj = ResourceManager.GetObject("icon_pan2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap item_ltr2 {
            get {
                object obj = ResourceManager.GetObject("item_ltr2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap item_rtl2 {
            get {
                object obj = ResourceManager.GetObject("item_rtl2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap item2 {
            get {
                object obj = ResourceManager.GetObject("item2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewRandomGeometry2 {
            get {
                object obj = ResourceManager.GetObject("NewRandomGeometry2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pan1 {
            get {
                object obj = ResourceManager.GetObject("pan1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pan3 {
            get {
                object obj = ResourceManager.GetObject("pan3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIE_DIAGRAM {
            get {
                object obj = ResourceManager.GetObject("PIE_DIAGRAM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIE_DIAGRAM1 {
            get {
                object obj = ResourceManager.GetObject("PIE_DIAGRAM1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap polygon1 {
            get {
                object obj = ResourceManager.GetObject("polygon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap polygon3 {
            get {
                object obj = ResourceManager.GetObject("polygon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap query1 {
            get {
                object obj = ResourceManager.GetObject("query1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap query3 {
            get {
                object obj = ResourceManager.GetObject("query3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Raster1 {
            get {
                object obj = ResourceManager.GetObject("Raster1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Raster3 {
            get {
                object obj = ResourceManager.GetObject("Raster3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh2 {
            get {
                object obj = ResourceManager.GetObject("Refresh2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RemoveTable1 {
            get {
                object obj = ResourceManager.GetObject("RemoveTable1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RemoveTable3 {
            get {
                object obj = ResourceManager.GetObject("RemoveTable3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_attention2 {
            get {
                object obj = ResourceManager.GetObject("s_attention2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_error22 {
            get {
                object obj = ResourceManager.GetObject("s_error22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_error3 {
            get {
                object obj = ResourceManager.GetObject("s_error3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_host2 {
            get {
                object obj = ResourceManager.GetObject("s_host2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_info2 {
            get {
                object obj = ResourceManager.GetObject("s_info2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_lang2 {
            get {
                object obj = ResourceManager.GetObject("s_lang2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_okay2 {
            get {
                object obj = ResourceManager.GetObject("s_okay2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_reload2 {
            get {
                object obj = ResourceManager.GetObject("s_reload2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_status2 {
            get {
                object obj = ResourceManager.GetObject("s_status2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_success2 {
            get {
                object obj = ResourceManager.GetObject("s_success2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s_warn2 {
            get {
                object obj = ResourceManager.GetObject("s_warn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sport {
            get {
                object obj = ResourceManager.GetObject("sport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tools {
            get {
                object obj = ResourceManager.GetObject("Tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tools1 {
            get {
                object obj = ResourceManager.GetObject("Tools1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tools3 {
            get {
                object obj = ResourceManager.GetObject("Tools3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolsbasic1 {
            get {
                object obj = ResourceManager.GetObject("toolsbasic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolsbasic3 {
            get {
                object obj = ResourceManager.GetObject("toolsbasic3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Women_12 {
            get {
                object obj = ResourceManager.GetObject("Women_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Women2 {
            get {
                object obj = ResourceManager.GetObject("Women2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_In {
            get {
                object obj = ResourceManager.GetObject("Zoom_In", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_In_icon1616 {
            get {
                object obj = ResourceManager.GetObject("Zoom_In_icon1616", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_In_icon2424 {
            get {
                object obj = ResourceManager.GetObject("Zoom_In_icon2424", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_In_icon3232 {
            get {
                object obj = ResourceManager.GetObject("Zoom_In_icon3232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_In_icon4848 {
            get {
                object obj = ResourceManager.GetObject("Zoom_In_icon4848", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_Out {
            get {
                object obj = ResourceManager.GetObject("Zoom_Out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_Out_icon1616 {
            get {
                object obj = ResourceManager.GetObject("Zoom_Out_icon1616", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_Out_icon2424 {
            get {
                object obj = ResourceManager.GetObject("Zoom_Out_icon2424", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_Out_icon3232 {
            get {
                object obj = ResourceManager.GetObject("Zoom_Out_icon3232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_Out_icon4848 {
            get {
                object obj = ResourceManager.GetObject("Zoom_Out_icon4848", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomToExtents2 {
            get {
                object obj = ResourceManager.GetObject("ZoomToExtents2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
