//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tripodmaps.ncSearchGeo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices", ConfigurationName="ncSearchGeo.geoservicesSoap")]
    public interface geoservicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/geocode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.geocoderesult geocode(long UserID, string Address, string Street, string POI, string City, string State, string ZIP, string Country, string SuppressError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getlocationinfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.locationinfo getlocationinfo(long UserID, double Longitude, double Latitude, string Language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getmap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.mapinfo getmap(long UserID, double Longitude, double Latitude, double Northing, double Easting, int ImageWidth, int ImageHeight, string Datasourc, bool OverviewFlag, string Language, string Icon, string MapStyle, string Objects);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getmapEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.mapinfo getmapEx(long UserID, double Longitude, double Latitude, double Northing, double Easting, int ImageWidth, int ImageHeight, string ImageFormat, string Datasourc, bool OverviewFlag, string Language, string Icon, string MapStyle, string Objects);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getmapbybr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.mapbybr getmapbybr(long UserID, double SouthwestLongitude, double SouthwestLatitude, double NortheastLongitude, double NortheastLatitude, int ImageWidth, int ImageHeight, bool OverviewFlag, string Datasourc, string Language, string Icon, string MapStyle, string Objects);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getmapbybrEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.mapbybr getmapbybrEx(long UserID, double SouthwestLongitude, double SouthwestLatitude, double NortheastLongitude, double NortheastLatitude, int ImageWidth, int ImageHeight, string ImageFormat, bool OverviewFlag, string Datasourc, string Language, string Icon, string MapStyle, string Objects);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.searchresult search(long UserID, double Longitude, double Latitude, double Radius, string Category, string Data_Source, string Language, bool ShowMap, int ImageWidth, int ImageHeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/searchEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.searchresult searchEx(long UserID, double Longitude, double Latitude, double Radius, string Category, string Data_Source, string Language, bool ShowMap, int ImageWidth, int ImageHeight, string ImageFormat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/gettrafficinfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.trafficinfo gettrafficinfo(long UserID, double Longitude, double Latitude, double Radius, string Language, bool ShowMap, int ImageWidth, int ImageHeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/gettrafficinfoEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.trafficinfo gettrafficinfoEx(long UserID, double Longitude, double Latitude, double Radius, string Language, bool ShowMap, int ImageWidth, int ImageHeight, string ImageFormat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getdirections", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.directionsinfo getdirections(long UserID, double StartLongitude, double StartLatitude, double EndLongitude, double EndLatitude, string Criterion, string Distance_Unit, string Language, bool ShowMap, int ImageWidth, int ImageHeight, bool ShowWaypoints);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getdirectionsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.directionsinfo getdirectionsEx(long UserID, double StartLongitude, double StartLatitude, double EndLongitude, double EndLatitude, string Criterion, string Distance_Unit, string Language, bool ShowMap, int ImageWidth, int ImageHeight, string ImageFormat, bool ShowWaypoints);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getdirectionsmp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.mpdirectionsinfo getdirectionsmp(long UserID, LatLong[] MPoints, string Criterion, string Distance_Unit, string Language, bool ShowMap, int ImageWidth, int ImageHeight, bool ShowWaypoints);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mlbs.net/nacgeoservices/geoservices/getdirectionsmpEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tripodmaps.ncSearchGeo.mpdirectionsinfo getdirectionsmpEx(long UserID, LatLong[] MPoints, string Criterion, string Distance_Unit, string Language, bool ShowMap, int ImageWidth, int ImageHeight, string ImageFormat, bool ShowWaypoints);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class geocoderesult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inputField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private string nACField;
        
        private string matchtypeField;
        
        private string matchaccuracyField;
        
        private string streetField;
        
        private string cityField;
        
        private string stateField;
        
        private string zIPField;
        
        private string countryField;
        
        private string alternativesField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
                this.RaisePropertyChanged("Input");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NAC {
            get {
                return this.nACField;
            }
            set {
                this.nACField = value;
                this.RaisePropertyChanged("NAC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Matchtype {
            get {
                return this.matchtypeField;
            }
            set {
                this.matchtypeField = value;
                this.RaisePropertyChanged("Matchtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Matchaccuracy {
            get {
                return this.matchaccuracyField;
            }
            set {
                this.matchaccuracyField = value;
                this.RaisePropertyChanged("Matchaccuracy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ZIP {
            get {
                return this.zIPField;
            }
            set {
                this.zIPField = value;
                this.RaisePropertyChanged("ZIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Alternatives {
            get {
                return this.alternativesField;
            }
            set {
                this.alternativesField = value;
                this.RaisePropertyChanged("Alternatives");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class mpdirectionsinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LatLong[] mPointsField;
        
        private string criterionField;
        
        private string languageField;
        
        private string distance_UnitField;
        
        private double distanceField;
        
        private double drivingTimeField;
        
        private string directionsField;
        
        private bool showMapField;
        
        private ImageData mapField;
        
        private bool showWaypointsField;
        
        private string waypointsField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LatLong[] MPoints {
            get {
                return this.mPointsField;
            }
            set {
                this.mPointsField = value;
                this.RaisePropertyChanged("MPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criterion {
            get {
                return this.criterionField;
            }
            set {
                this.criterionField = value;
                this.RaisePropertyChanged("Criterion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Distance_Unit {
            get {
                return this.distance_UnitField;
            }
            set {
                this.distance_UnitField = value;
                this.RaisePropertyChanged("Distance_Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double DrivingTime {
            get {
                return this.drivingTimeField;
            }
            set {
                this.drivingTimeField = value;
                this.RaisePropertyChanged("DrivingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Directions {
            get {
                return this.directionsField;
            }
            set {
                this.directionsField = value;
                this.RaisePropertyChanged("Directions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ShowMap {
            get {
                return this.showMapField;
            }
            set {
                this.showMapField = value;
                this.RaisePropertyChanged("ShowMap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ImageData Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("Map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool ShowWaypoints {
            get {
                return this.showWaypointsField;
            }
            set {
                this.showWaypointsField = value;
                this.RaisePropertyChanged("ShowWaypoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Waypoints {
            get {
                return this.waypointsField;
            }
            set {
                this.waypointsField = value;
                this.RaisePropertyChanged("Waypoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s.mappoint.net/mappoint-30/")]
    public partial class LatLong : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double latitudeField;
        
        private double longitudeField;
        
        public LatLong() {
            this.latitudeField = 0;
            this.longitudeField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class ImageData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] bitsField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] bits {
            get {
                return this.bitsField;
            }
            set {
                this.bitsField = value;
                this.RaisePropertyChanged("bits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class directionsinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double startLongitudeField;
        
        private double startLatitudeField;
        
        private double endLongitudeField;
        
        private double endLatitudeField;
        
        private string criterionField;
        
        private string languageField;
        
        private string distance_UnitField;
        
        private double distanceField;
        
        private double drivingTimeField;
        
        private string directionsField;
        
        private bool showMapField;
        
        private ImageData mapField;
        
        private bool showWaypointsField;
        
        private string waypointsField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double StartLongitude {
            get {
                return this.startLongitudeField;
            }
            set {
                this.startLongitudeField = value;
                this.RaisePropertyChanged("StartLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double StartLatitude {
            get {
                return this.startLatitudeField;
            }
            set {
                this.startLatitudeField = value;
                this.RaisePropertyChanged("StartLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double EndLongitude {
            get {
                return this.endLongitudeField;
            }
            set {
                this.endLongitudeField = value;
                this.RaisePropertyChanged("EndLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double EndLatitude {
            get {
                return this.endLatitudeField;
            }
            set {
                this.endLatitudeField = value;
                this.RaisePropertyChanged("EndLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Criterion {
            get {
                return this.criterionField;
            }
            set {
                this.criterionField = value;
                this.RaisePropertyChanged("Criterion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Distance_Unit {
            get {
                return this.distance_UnitField;
            }
            set {
                this.distance_UnitField = value;
                this.RaisePropertyChanged("Distance_Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double DrivingTime {
            get {
                return this.drivingTimeField;
            }
            set {
                this.drivingTimeField = value;
                this.RaisePropertyChanged("DrivingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Directions {
            get {
                return this.directionsField;
            }
            set {
                this.directionsField = value;
                this.RaisePropertyChanged("Directions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool ShowMap {
            get {
                return this.showMapField;
            }
            set {
                this.showMapField = value;
                this.RaisePropertyChanged("ShowMap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public ImageData Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("Map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool ShowWaypoints {
            get {
                return this.showWaypointsField;
            }
            set {
                this.showWaypointsField = value;
                this.RaisePropertyChanged("ShowWaypoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Waypoints {
            get {
                return this.waypointsField;
            }
            set {
                this.waypointsField = value;
                this.RaisePropertyChanged("Waypoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class trafficinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double longitudeField;
        
        private double latitudeField;
        
        private double radiusField;
        
        private string languageField;
        
        private string incidentsField;
        
        private bool showMapField;
        
        private string hotspotsField;
        
        private int imageWidthField;
        
        private int imageHeightField;
        
        private ImageData mapField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
                this.RaisePropertyChanged("Radius");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Incidents {
            get {
                return this.incidentsField;
            }
            set {
                this.incidentsField = value;
                this.RaisePropertyChanged("Incidents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ShowMap {
            get {
                return this.showMapField;
            }
            set {
                this.showMapField = value;
                this.RaisePropertyChanged("ShowMap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Hotspots {
            get {
                return this.hotspotsField;
            }
            set {
                this.hotspotsField = value;
                this.RaisePropertyChanged("Hotspots");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ImageWidth {
            get {
                return this.imageWidthField;
            }
            set {
                this.imageWidthField = value;
                this.RaisePropertyChanged("ImageWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ImageHeight {
            get {
                return this.imageHeightField;
            }
            set {
                this.imageHeightField = value;
                this.RaisePropertyChanged("ImageHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ImageData Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("Map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class searchresult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double longitudeField;
        
        private double latitudeField;
        
        private double radiusField;
        
        private string categoryField;
        
        private string data_SourceField;
        
        private string languageField;
        
        private string entitiesField;
        
        private bool showMapField;
        
        private string hotspotsField;
        
        private int imageWidthField;
        
        private int imageHeightField;
        
        private ImageData mapField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
                this.RaisePropertyChanged("Radius");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Data_Source {
            get {
                return this.data_SourceField;
            }
            set {
                this.data_SourceField = value;
                this.RaisePropertyChanged("Data_Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
                this.RaisePropertyChanged("Entities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ShowMap {
            get {
                return this.showMapField;
            }
            set {
                this.showMapField = value;
                this.RaisePropertyChanged("ShowMap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Hotspots {
            get {
                return this.hotspotsField;
            }
            set {
                this.hotspotsField = value;
                this.RaisePropertyChanged("Hotspots");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ImageWidth {
            get {
                return this.imageWidthField;
            }
            set {
                this.imageWidthField = value;
                this.RaisePropertyChanged("ImageWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int ImageHeight {
            get {
                return this.imageHeightField;
            }
            set {
                this.imageHeightField = value;
                this.RaisePropertyChanged("ImageHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public ImageData Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("Map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class mapbybr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double southwestLongitudeField;
        
        private double southwestLatitudeField;
        
        private double northeastLongitudeField;
        
        private double northeastLatitudeField;
        
        private int imageWidthField;
        
        private int imageHeightField;
        
        private string datasourceField;
        
        private bool overviewFlagField;
        
        private string languageField;
        
        private string iconField;
        
        private string mapStyleField;
        
        private string hotspotsField;
        
        private ImageData mapField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double SouthwestLongitude {
            get {
                return this.southwestLongitudeField;
            }
            set {
                this.southwestLongitudeField = value;
                this.RaisePropertyChanged("SouthwestLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double SouthwestLatitude {
            get {
                return this.southwestLatitudeField;
            }
            set {
                this.southwestLatitudeField = value;
                this.RaisePropertyChanged("SouthwestLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double NortheastLongitude {
            get {
                return this.northeastLongitudeField;
            }
            set {
                this.northeastLongitudeField = value;
                this.RaisePropertyChanged("NortheastLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double NortheastLatitude {
            get {
                return this.northeastLatitudeField;
            }
            set {
                this.northeastLatitudeField = value;
                this.RaisePropertyChanged("NortheastLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ImageWidth {
            get {
                return this.imageWidthField;
            }
            set {
                this.imageWidthField = value;
                this.RaisePropertyChanged("ImageWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ImageHeight {
            get {
                return this.imageHeightField;
            }
            set {
                this.imageHeightField = value;
                this.RaisePropertyChanged("ImageHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Datasource {
            get {
                return this.datasourceField;
            }
            set {
                this.datasourceField = value;
                this.RaisePropertyChanged("Datasource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool OverviewFlag {
            get {
                return this.overviewFlagField;
            }
            set {
                this.overviewFlagField = value;
                this.RaisePropertyChanged("OverviewFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
                this.RaisePropertyChanged("Icon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MapStyle {
            get {
                return this.mapStyleField;
            }
            set {
                this.mapStyleField = value;
                this.RaisePropertyChanged("MapStyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Hotspots {
            get {
                return this.hotspotsField;
            }
            set {
                this.hotspotsField = value;
                this.RaisePropertyChanged("Hotspots");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public ImageData Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("Map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class mapinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double longitudeField;
        
        private double latitudeField;
        
        private double northingField;
        
        private double eastingField;
        
        private int imageWidthField;
        
        private int imageHeightField;
        
        private string datasourceField;
        
        private bool overviewFlagField;
        
        private string languageField;
        
        private string iconField;
        
        private string mapStyleField;
        
        private string hotspotsField;
        
        private ImageData mapField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Northing {
            get {
                return this.northingField;
            }
            set {
                this.northingField = value;
                this.RaisePropertyChanged("Northing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Easting {
            get {
                return this.eastingField;
            }
            set {
                this.eastingField = value;
                this.RaisePropertyChanged("Easting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ImageWidth {
            get {
                return this.imageWidthField;
            }
            set {
                this.imageWidthField = value;
                this.RaisePropertyChanged("ImageWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ImageHeight {
            get {
                return this.imageHeightField;
            }
            set {
                this.imageHeightField = value;
                this.RaisePropertyChanged("ImageHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Datasource {
            get {
                return this.datasourceField;
            }
            set {
                this.datasourceField = value;
                this.RaisePropertyChanged("Datasource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool OverviewFlag {
            get {
                return this.overviewFlagField;
            }
            set {
                this.overviewFlagField = value;
                this.RaisePropertyChanged("OverviewFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
                this.RaisePropertyChanged("Icon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MapStyle {
            get {
                return this.mapStyleField;
            }
            set {
                this.mapStyleField = value;
                this.RaisePropertyChanged("MapStyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Hotspots {
            get {
                return this.hotspotsField;
            }
            set {
                this.hotspotsField = value;
                this.RaisePropertyChanged("Hotspots");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public ImageData Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("Map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mlbs.net/nacgeoservices/geoservices")]
    public partial class locationinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double longitudeField;
        
        private double latitudeField;
        
        private string languageField;
        
        private string addressesField;
        
        private string placesField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("Addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Places {
            get {
                return this.placesField;
            }
            set {
                this.placesField = value;
                this.RaisePropertyChanged("Places");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface geoservicesSoapChannel : Tripodmaps.ncSearchGeo.geoservicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class geoservicesSoapClient : System.ServiceModel.ClientBase<Tripodmaps.ncSearchGeo.geoservicesSoap>, Tripodmaps.ncSearchGeo.geoservicesSoap {
        
        public geoservicesSoapClient() {
        }
        
        public geoservicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public geoservicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public geoservicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public geoservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tripodmaps.ncSearchGeo.geocoderesult geocode(long UserID, string Address, string Street, string POI, string City, string State, string ZIP, string Country, string SuppressError) {
            return base.Channel.geocode(UserID, Address, Street, POI, City, State, ZIP, Country, SuppressError);
        }
        
        public Tripodmaps.ncSearchGeo.locationinfo getlocationinfo(long UserID, double Longitude, double Latitude, string Language) {
            return base.Channel.getlocationinfo(UserID, Longitude, Latitude, Language);
        }
        
        public Tripodmaps.ncSearchGeo.mapinfo getmap(long UserID, double Longitude, double Latitude, double Northing, double Easting, int ImageWidth, int ImageHeight, string Datasourc, bool OverviewFlag, string Language, string Icon, string MapStyle, string Objects) {
            return base.Channel.getmap(UserID, Longitude, Latitude, Northing, Easting, ImageWidth, ImageHeight, Datasourc, OverviewFlag, Language, Icon, MapStyle, Objects);
        }
        
        public Tripodmaps.ncSearchGeo.mapinfo getmapEx(long UserID, double Longitude, double Latitude, double Northing, double Easting, int ImageWidth, int ImageHeight, string ImageFormat, string Datasourc, bool OverviewFlag, string Language, string Icon, string MapStyle, string Objects) {
            return base.Channel.getmapEx(UserID, Longitude, Latitude, Northing, Easting, ImageWidth, ImageHeight, ImageFormat, Datasourc, OverviewFlag, Language, Icon, MapStyle, Objects);
        }
        
        public Tripodmaps.ncSearchGeo.mapbybr getmapbybr(long UserID, double SouthwestLongitude, double SouthwestLatitude, double NortheastLongitude, double NortheastLatitude, int ImageWidth, int ImageHeight, bool OverviewFlag, string Datasourc, string Language, string Icon, string MapStyle, string Objects) {
            return base.Channel.getmapbybr(UserID, SouthwestLongitude, SouthwestLatitude, NortheastLongitude, NortheastLatitude, ImageWidth, ImageHeight, OverviewFlag, Datasourc, Language, Icon, MapStyle, Objects);
        }
        
        public Tripodmaps.ncSearchGeo.mapbybr getmapbybrEx(long UserID, double SouthwestLongitude, double SouthwestLatitude, double NortheastLongitude, double NortheastLatitude, int ImageWidth, int ImageHeight, string ImageFormat, bool OverviewFlag, string Datasourc, string Language, string Icon, string MapStyle, string Objects) {
            return base.Channel.getmapbybrEx(UserID, SouthwestLongitude, SouthwestLatitude, NortheastLongitude, NortheastLatitude, ImageWidth, ImageHeight, ImageFormat, OverviewFlag, Datasourc, Language, Icon, MapStyle, Objects);
        }
        
        public Tripodmaps.ncSearchGeo.searchresult search(long UserID, double Longitude, double Latitude, double Radius, string Category, string Data_Source, string Language, bool ShowMap, int ImageWidth, int ImageHeight) {
            return base.Channel.search(UserID, Longitude, Latitude, Radius, Category, Data_Source, Language, ShowMap, ImageWidth, ImageHeight);
        }
        
        public Tripodmaps.ncSearchGeo.searchresult searchEx(long UserID, double Longitude, double Latitude, double Radius, string Category, string Data_Source, string Language, bool ShowMap, int ImageWidth, int ImageHeight, string ImageFormat) {
            return base.Channel.searchEx(UserID, Longitude, Latitude, Radius, Category, Data_Source, Language, ShowMap, ImageWidth, ImageHeight, ImageFormat);
        }
        
        public Tripodmaps.ncSearchGeo.trafficinfo gettrafficinfo(long UserID, double Longitude, double Latitude, double Radius, string Language, bool ShowMap, int ImageWidth, int ImageHeight) {
            return base.Channel.gettrafficinfo(UserID, Longitude, Latitude, Radius, Language, ShowMap, ImageWidth, ImageHeight);
        }
        
        public Tripodmaps.ncSearchGeo.trafficinfo gettrafficinfoEx(long UserID, double Longitude, double Latitude, double Radius, string Language, bool ShowMap, int ImageWidth, int ImageHeight, string ImageFormat) {
            return base.Channel.gettrafficinfoEx(UserID, Longitude, Latitude, Radius, Language, ShowMap, ImageWidth, ImageHeight, ImageFormat);
        }
        
        public Tripodmaps.ncSearchGeo.directionsinfo getdirections(long UserID, double StartLongitude, double StartLatitude, double EndLongitude, double EndLatitude, string Criterion, string Distance_Unit, string Language, bool ShowMap, int ImageWidth, int ImageHeight, bool ShowWaypoints) {
            return base.Channel.getdirections(UserID, StartLongitude, StartLatitude, EndLongitude, EndLatitude, Criterion, Distance_Unit, Language, ShowMap, ImageWidth, ImageHeight, ShowWaypoints);
        }
        
        public Tripodmaps.ncSearchGeo.directionsinfo getdirectionsEx(long UserID, double StartLongitude, double StartLatitude, double EndLongitude, double EndLatitude, string Criterion, string Distance_Unit, string Language, bool ShowMap, int ImageWidth, int ImageHeight, string ImageFormat, bool ShowWaypoints) {
            return base.Channel.getdirectionsEx(UserID, StartLongitude, StartLatitude, EndLongitude, EndLatitude, Criterion, Distance_Unit, Language, ShowMap, ImageWidth, ImageHeight, ImageFormat, ShowWaypoints);
        }
        
        public Tripodmaps.ncSearchGeo.mpdirectionsinfo getdirectionsmp(long UserID, LatLong[] MPoints, string Criterion, string Distance_Unit, string Language, bool ShowMap, int ImageWidth, int ImageHeight, bool ShowWaypoints) {
            return base.Channel.getdirectionsmp(UserID, MPoints, Criterion, Distance_Unit, Language, ShowMap, ImageWidth, ImageHeight, ShowWaypoints);
        }
        
        public Tripodmaps.ncSearchGeo.mpdirectionsinfo getdirectionsmpEx(long UserID, LatLong[] MPoints, string Criterion, string Distance_Unit, string Language, bool ShowMap, int ImageWidth, int ImageHeight, string ImageFormat, bool ShowWaypoints) {
            return base.Channel.getdirectionsmpEx(UserID, MPoints, Criterion, Distance_Unit, Language, ShowMap, ImageWidth, ImageHeight, ImageFormat, ShowWaypoints);
        }
    }
}
